# Generated by Django 4.1.7 on 2023-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
