# Generated by Django 4.1.7 on 2023-05-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
