# Generated by Django 4.1.7 on 2023-05-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
