# Generated by Django 4.1.7 on 2023-05-13 13:12

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name=time.thread_time_ns)),
            ],
        ),
        migrations.CreateModel(
            name='Mont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaer', models.IntegerField()),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='web.hour')),
                ('mont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='web.mont')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='web.time')),
            ],
        ),
    ]
