# Generated by Django 4.1.7 on 2023-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_turn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='day',
            field=models.IntegerField(blank=True, max_length=31, null=True),
        ),
    ]
