# Generated by Django 4.1.7 on 2023-05-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_time_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
                ('mount', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('hour', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
