# Generated by Django 4.1.7 on 2023-06-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_save_turn_alter_time_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save_turn',
        ),
    ]
